spring.application.name=primetrade-backend

server.port=8080

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/primetrade_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:YOUR_PASSWORD}

# ===============================
# JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# JWT Configuration
# ===============================
app.jwt.secret=${JWT_SECRET:PrimetradeBackendSecretKeyForJwtAuthentication123456789}
app.jwt.expiration-ms=86400000

# ===============================
# Swagger / OpenAPI
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
